# Site settings
title: 縦書きWeb普及委員会
email: tategaki@est.co.jp
description: 縦書きWeb普及委員会は、日本の文化である縦書きを利用したWebコンテンツの普及促進に取り組んでいます。
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://tategaki.github.io" # the base hostname & protocol for your site
domain_name: "tategaki.github.io"
twitter_username: nil
github_username:  nil

# Build settings
markdown: kramdown
kramdown:
  input: GFM

highlighter: pygments